[build]
base = "fakturowanie-frontend"
command = "npm ci && npm run build"
publish = "dist"


[build.environment]
NODE_VERSION = "20"


# --- API proxy: najpierw /api/* -> Railway ---
[[redirects]]
from = "/api/*"
to = "https://fakturowanie-node-react-production.up.railway.app/:splat"
status = 200
force = true

# --- SPA fallback: na końcu ---
[[redirects]]
from = "/*"
to = "/index.html"
status = 200