[build]
command = "npm ci && npm run build"
publish = "dist"


[build.environment]
NODE_VERSION = "20"

# Single Page App: przekieruj wszystkie ścieżki do index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
