[build]
# Netlify wejdzie do podkatalogu frontu i tam wykona instalację + build
base = "fakturowanie-frontend"
command = "npm ci && npm run build"
publish = "dist"

# (opcjonalnie) ustaw wersję Node jeżeli nie używasz .nvmrc
[build.environment]
NODE_VERSION = "20"

# Single Page App: przekieruj wszystkie ścieżki do index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# (opcjonalnie) pomiń build, jeśli zmienił się tylko backend
# Komenda ma zwrócić 0 => build pominięty
# Tu: jeśli różnice poza katalogiem frontu są puste, to pomiń
# (wymaga włączonego cachowania w Netlify, domyślnie jest)
[build]
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ':!fakturowanie-frontend/**'"
